### ISSUE TITLE
Exception thrown when start application

### ISSUE THREAD

**Issue by Walpurisnacht** [limyz/DTXmaniaNX#39]
Just when I started the application throw exception but if ignore the exception by clicking Continue the game still works
Below is the log

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DTXMania.CDTXMania.Draw(GameTime gameTime)
   at SampleFramework.Game.DrawFrame()
   at SampleFramework.Game.Window_Paint(Object sender, PaintEventArgs e)
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Form.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at SampleFramework.GameWindow.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9151 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
DTXManiaGR
    Assembly Version: 3.6.2.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/DTXManiaXG(ver.K)%20Ver3.62c2/DTXManiaGR.exe
----------------------------------------
FDK
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.0.0
    CodeBase: file:///D:/DTXManiaXG(ver.K)%20Ver3.62c2/FDK.DLL
----------------------------------------
SlimDXc_net20x86_Jun2010
    Assembly Version: 1002.0.10.43
    Win32 Version: 
    CodeBase: file:///D:/DTXManiaXG(ver.K)%20Ver3.62c2/SlimDXc_net20x86_Jun2010.DLL
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9147 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
msvcm90
    Assembly Version: 9.0.30729.9619
    Win32 Version: 9.00.30729.9619
    CodeBase: file:///C:/WINDOWS/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9619_none_508d9c7abcbd32b6/msvcm90.dll
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9154 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Bass.Net
    Assembly Version: 2.4.10.3
    Win32 Version: 2.4.10.3
    CodeBase: file:///D:/DTXManiaXG(ver.K)%20Ver3.62c2/Bass.Net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9153 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by ericpignet** [comment]
Could you set OutputLog=1 in your Config.ini in [Log] section, reproduce the issue and copy the content of the DTXManiaLog.txt file into this bug report?

**Comment by Walpurisnacht** [comment]
Here is the log
I think the exception was thrown before writing to the logger

```
DTXMania powered by YAMAHA Silent Session Drums
Release: Ver3.62cGD(200803)

2020/08/28 20:08:25.835 [INFO] ----------------------
2020/08/28 20:08:25.836 [INFO] ■ アプリケーションの初期化
2020/08/28 20:08:25.836 [INFO] OS Version: Microsoft Windows NT 6.2.9200.0
2020/08/28 20:08:25.836 [INFO] ProcessorCount: 12
2020/08/28 20:08:25.837 [INFO] CLR Version: 2.0.50727.9151
2020/08/28 20:08:31.596 [INFO] スキンの初期化を行います。
2020/08/28 20:08:31.684 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\DTXManiaV2\
2020/08/28 20:08:31.707 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\EXCHAIN\
2020/08/28 20:08:31.740 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\GITADORA\
2020/08/28 20:08:31.760 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\Matixx\
2020/08/28 20:08:31.788 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\NEXTAGE\
2020/08/28 20:08:31.826 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\OverDrive\
2020/08/28 20:08:31.836 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\Re Evolve\
2020/08/28 20:08:31.869 [INFO]     SkinPath検出: D:\DTXManiaXG(ver.K) Ver3.62c2\System\Tri-Boost\
2020/08/28 20:08:31.869 [INFO]     SkinPath入力: D:\DTXManiaXG(ver.K) Ver3.62c2\System\NEXTAGE\
2020/08/28 20:08:31.872 [INFO]     SkinPath設定: D:\DTXManiaXG(ver.K) Ver3.62c2\System\NEXTAGE\
2020/08/28 20:08:31.873 [INFO]     スキンの初期化を完了しました。
2020/08/28 20:08:31.873 [INFO] タイマの初期化を行います。
2020/08/28 20:08:31.874 [INFO]     タイマの初期化を完了しました。
2020/08/28 20:08:31.874 [INFO] FPSカウンタの初期化を行います。
2020/08/28 20:08:31.874 [INFO]     FPSカウンタを生成しました。
2020/08/28 20:08:31.875 [INFO] 文字コンソールの初期化を行います。
2020/08/28 20:08:31.875 [INFO]     文字コンソールを生成しました。
2020/08/28 20:08:31.924 [INFO]     文字コンソールを活性化しました。
2020/08/28 20:08:31.924 [INFO]     文字コンソールの初期化を完了しました。
2020/08/28 20:08:31.924 [INFO] DirectInput, MIDI入力の初期化を行います。
2020/08/28 20:08:31.955 [INFO]     Keyboard を生成しました。
2020/08/28 20:08:31.957 [INFO]     Mouse を生成しました。
2020/08/28 20:08:32.108 [INFO]     MIDI入力デバイス数: 0
2020/08/28 20:08:32.108 [INFO]     DirectInput の初期化を完了しました。
2020/08/28 20:08:32.108 [INFO] パッドの初期化を行います。
2020/08/28 20:08:32.108 [INFO]     パッドの初期化を完了しました。
2020/08/28 20:08:32.108 [INFO] サウンドデバイスの初期化を行います。
2020/08/28 20:08:32.115 [INFO]     DirectSound の初期化を開始します。
2020/08/28 20:08:32.198 [INFO]     DirectSound を初期化しました。(Priority)
2020/08/28 20:08:32.199 [INFO]     サウンドデバイスの初期化を完了しました。
2020/08/28 20:08:32.199 [INFO] 曲リストの初期化を行います。
2020/08/28 20:08:32.200 [INFO]     曲リストの初期化を完了しました。
2020/08/28 20:08:32.233 [INFO] プラグインの検索と生成を行います。
2020/08/28 20:08:32.234 [WARNING]     プラグインフォルダが存在しません。(D:\DTXManiaXG(ver.K) Ver3.62c2\Plugins\)
2020/08/28 20:08:32.234 [INFO]     プラグインの検索と生成を完了しました。
2020/08/28 20:08:32.234 [INFO] アプリケーションの初期化を完了しました。
2020/08/28 20:08:32.235 [INFO] ----------------------
2020/08/28 20:08:32.235 [INFO] ■ 起動
2020/08/28 20:08:32.235 [INFO] 起動ステージを活性化します。
2020/08/28 20:08:32.303 [INFO]     起動ステージの活性化を完了しました。
2020/08/28 20:08:32.317 [INFO] 0) システムサウンドを構築します。
2020/08/28 20:08:32.350 [INFO]     システムサウンドを読み込みました。(Sounds\Move.ogg)
2020/08/28 20:08:32.361 [INFO]     システムサウンドを読み込みました。(Sounds\Decide.ogg)
2020/08/28 20:08:32.367 [INFO]     システムサウンドを読み込みました。(Sounds\Change.ogg)
2020/08/28 20:08:32.374 [INFO]     システムサウンドを読み込みました。(Sounds\Cancel.ogg)
2020/08/28 20:08:32.408 [INFO]     システムサウンドを読み込みました。(Sounds\Audience.ogg)
2020/08/28 20:08:32.453 [INFO]     システムサウンドを読み込みました。(Sounds\Game start.ogg)
2020/08/28 20:08:32.474 [INFO]     システムサウンドを読み込みました。(Sounds\Full combo.ogg)
2020/08/28 20:08:32.493 [INFO]     システムサウンドを読み込みました。(Sounds\Excellent.ogg)
2020/08/28 20:08:32.513 [INFO]     システムサウンドを読み込みました。(Sounds\New Record.ogg)
2020/08/28 20:08:32.513 [WARNING]     システムサウンドが存在しません。(Sounds\MusicDecide.ogg)
2020/08/28 20:08:32.514 [WARNING]     システムサウンドが存在しません。(Sounds\Novice.ogg)
2020/08/28 20:08:32.514 [WARNING]     システムサウンドが存在しません。(Sounds\Regular.ogg)
2020/08/28 20:08:32.514 [WARNING]     システムサウンドが存在しません。(Sounds\Expert.ogg)
2020/08/28 20:08:32.531 [INFO]     システムサウンドを読み込みました。(Sounds\Master.ogg)
2020/08/28 20:08:32.531 [WARNING]     システムサウンドが存在しません。(Sounds\SelectMusic.ogg)
2020/08/28 20:08:32.548 [INFO]     システムサウンドを読み込みました。(Sounds\Basic.ogg)
2020/08/28 20:08:32.565 [INFO]     システムサウンドを読み込みました。(Sounds\Advanced.ogg)
2020/08/28 20:08:32.582 [INFO]     システムサウンドを読み込みました。(Sounds\Extreme.ogg)
2020/08/28 20:08:32.582 [INFO] 1) songlist.dbを読み込みます。
2020/08/28 20:08:32.596 [INFO]     songlist.db の読み込みを完了しました。[0スコア]
2020/08/28 20:08:32.596 [INFO] 2) songs.db を読み込みます。
2020/08/28 20:08:32.601 [INFO]     songs.db の読み込みを完了しました。[0スコア]
2020/08/28 20:08:32.601 [INFO] 起動所要時間: 00:00:00.2837539
2020/08/28 20:08:32.602 [INFO] 起動ステージを非活性化します。
2020/08/28 20:08:32.608 [INFO]     起動ステージの非活性化を完了しました。
2020/08/28 20:08:32.609 [INFO] ----------------------
2020/08/28 20:08:32.609 [INFO] ■ タイトル
2020/08/28 20:08:32.609 [INFO] タイトルステージを活性化します。
2020/08/28 20:08:32.675 [INFO]     タイトルステージの活性化を完了しました。
2020/08/28 20:08:32.702 [INFO] ★曲データ検索スレッドを起動しました。
2020/08/28 20:08:32.704 [INFO] enum2) 曲データを検索します。
2020/08/28 20:08:32.704 [INFO]     検索パス: D:\DTXManiaXG(ver.K) Ver3.62c2\.\
2020/08/28 20:08:33.528 [INFO]     曲データの検索を完了しました。[0曲0スコア]
2020/08/28 20:08:33.528 [INFO] enum3) songs.db の情報を曲リストへ反映します。
2020/08/28 20:08:33.530 [INFO]     曲リストへの反映を完了しました。[0/0スコア]
2020/08/28 20:08:33.530 [INFO] 0, 0
2020/08/28 20:08:33.530 [INFO] enum4) songs.db になかった曲データ[0スコア]の情報をファイルから読み込んで反映します。
2020/08/28 20:08:33.532 [INFO]     曲データへの反映を完了しました。[0/0スコア]
2020/08/28 20:08:33.532 [INFO] enum5) 曲リストへの後処理を適用します。
2020/08/28 20:08:33.536 [INFO]     曲リストへの後処理を完了しました。
2020/08/28 20:08:33.536 [INFO] enum6) 曲データの情報を songs.db へ出力します。
2020/08/28 20:08:33.537 [INFO]     songs.db への出力を完了しました。[0スコア]
2020/08/28 20:08:33.537 [INFO] enum7) 曲データの情報を songlist.db へ出力します。
2020/08/28 20:08:33.540 [INFO]     songlist.db への出力を完了しました。[0スコア]
2020/08/28 20:08:33.541 [INFO] 曲探索所要時間: 00:00:00.8356270
2020/08/28 20:08:38.490 [INFO] ----------------------
2020/08/28 20:08:38.490 [INFO] ■ アプリケーションの終了
2020/08/28 20:08:38.490 [INFO] 曲検索actの終了処理を行います。
2020/08/28 20:08:38.490 [INFO]     曲検索actの終了処理を完了しました。
2020/08/28 20:08:38.491 [INFO] 現在のステージを終了します。
2020/08/28 20:08:38.491 [INFO]     タイトルステージを非活性化します。
2020/08/28 20:08:38.492 [INFO]         タイトルステージの非活性化を完了しました。
2020/08/28 20:08:38.493 [INFO]     現在のステージの終了処理を完了しました。
2020/08/28 20:08:38.493 [INFO] 曲リストの終了処理を行います。
2020/08/28 20:08:38.494 [INFO]     曲リストの終了処理を完了しました。
2020/08/28 20:08:38.494 [INFO] スキンの終了処理を行います。
2020/08/28 20:08:38.505 [INFO]     スキンの終了処理を完了しました。
2020/08/28 20:08:38.505 [INFO] DirectSound の終了処理を行います。
2020/08/28 20:08:38.515 [INFO]     DirectSound の終了処理を完了しました。
2020/08/28 20:08:38.516 [INFO] パッドの終了処理を行います。
2020/08/28 20:08:38.516 [INFO]     パッドの終了処理を完了しました。
2020/08/28 20:08:38.516 [INFO] DirectInput, MIDI入力の終了処理を行います。
2020/08/28 20:08:38.517 [INFO]     DirectInput, MIDI入力の終了処理を完了しました。
2020/08/28 20:08:38.517 [INFO] 文字コンソールの終了処理を行います。
2020/08/28 20:08:38.518 [INFO]     文字コンソールの終了処理を完了しました。
2020/08/28 20:08:38.518 [INFO] FPSカウンタの終了処理を行います。
2020/08/28 20:08:38.518 [INFO]     FPSカウンタの終了処理を完了しました。
2020/08/28 20:08:38.518 [INFO] タイマの終了処理を行います。
2020/08/28 20:08:38.518 [INFO]     タイマの終了処理を完了しました。
2020/08/28 20:08:38.518 [INFO] Config.ini を出力します。
2020/08/28 20:08:38.530 [INFO]     保存しました。(D:\DTXManiaXG(ver.K) Ver3.62c2\Config.ini)
2020/08/28 20:08:38.530 [INFO] アプリケーションの終了処理を完了しました。

遊んでくれてありがとう！
```

**Comment by limyz** [comment]
There's nothing unusual in the log and I can't replicate the issue on my end. Try switching skins or download another to see if the issue goes away.

**Comment by fisyher** [comment]
I was able to replicate this crash bug if Japanese IME keyboard is enabled **before** running DTXManiaGR. 
@Walpurisnacht Did you enable Japanese IME keyboard when you ran DTXManiaGR ?

**Comment by Walpurisnacht** [comment]
@fisyher Yes, my default IME is Japanese

**Comment by tanabotadtx** [comment]
I searched the same issue in original DTXMania (not VerK) and found https://osdn.net/projects/dtxmania/ticket/37775

Adding below code at the top of CDTXMania.Draw() seems to fix it:

if (Sound管理 == null) { return: }

**Comment by fisyher** [comment]
Verified that the code suggested by @tanabotadtx works to fix this issue.
